### ISSUE TITLE
Add JetComposite unit tests

### ISSUE THREAD

**Issue by jkwashbourne** [ChevronETC/Jets.jl#5]
JetComposite in src/Jets.jl but no unit tests

**Comment by samtkaplan** [comment]
unit tests for compositions are here: https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L259

and here:
https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L291

and here:
https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L321

and here:
https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L355

and here:
https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L388

and here:
https://github.com/ChevronETC/Jets.jl/blob/435313b9cd9ab2d91c6f31566e6b01f89113c5f2/test/runtests.jl#L401

I think the confusion is that the composition is exercised via `∘` rather than the `JetComposite` constructor directly.  Anyways, I guess there is not issue here and that this can be closed.
